### ISSUE TITLE
Error page gives no details + has templating error

### ISSUE THREAD

**Issue by jankeromnes** [cozy/cozy-proxy#100]
Just booted up my cozy, logged in, then saw this:

![cozyproblem](https://cloud.githubusercontent.com/assets/599268/6504688/2f6d59c6-c33a-11e4-9b89-864671f13a4b.png)

- It would be great to have some "details" or "logs" option or any indication of what went wrong.
- The link(s) is/are broken.

**Comment by jankeromnes** [comment]
Update: Refreshing cozy made the error screen disappear, but this bug is about problems with the error screen, not the problem that caused it to appear.

**Comment by frankrousseau** [comment]
Thank you @jankeromnes for reporting. First, we'll clean the link error. For the logs/details, it will probably takes more time to figure out what we could do.

**Comment by poupotte** [comment]
We have now details of error when we click on application icon and logs in status page. @jankeromnes , @frankrousseau, can we close this issue ?

**Comment by frankrousseau** [comment]
Yep, thank you @poupotte
