### ISSUE TITLE
AdBlockers display none some icons

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-proxy#119]
Icons related to sharing or web-service (see https://github.com/FortAwesome/Font-Awesome/issues/6403) are blocked by adblockers (https://github.com/FortAwesome/Font-Awesome/issues/1799).

I uggest we use only a subset of font-awesome icons (for performance) and use a custom prefix (using http://icomoon.io/app) to bypass this issue.

**Comment by tagliala** [comment]
The offending blocking list: https://easylist-downloads.adblockplus.org/fanboy-social.txt

It specifically addresses fontawesome, but be also aware of `icon-` prefix

**Comment by frankrousseau** [comment]
I think the bu is on the adblocker side. Not on the Cozy side. Font awesome does nothing harmful. Let's close this issue. Thank you @tagliala for the list!

**Comment by clochix** [comment]
IMHO, users don't care who's fault it is, they just see that Cozy doesn't work. Ad Blockers are pretty popular among geeks users, so I think that we should try to fix this issue, if there's an easy way to do it.

**Comment by m4dz** [comment]
Hi,

thanks @clochix, exactly my thoughts. @frankrousseau I'm so sorry, but I can't agree with you: you can't blame users for using an adblocker (which is common), but you can't reject the broken Ui to them so. As far as we are aware of this issue, I think we must handle a quick fix. Changing the icons names, maybe using the `cicn` prefix (stands for _cozy icon_), can be a simple workaround (e.g. icons will be called using the `cicn cicn-share`). And this can be easily done using icomoon app to generate only a subset of icons.
