### ISSUE TITLE
Experimental caldav & cardav routes fail when no instance.

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-proxy#141]
We could use the `request.host` to guess if we dont have an instance. 

Or better yet, display an error in a cozy-notification for the user to go configure its cozy settings.

**Comment by clochix** [comment]
cf [this thread](https://forum.cozy.io/t/davdroid-erreur-500/898/5).

**Comment by poupotte** [comment]
This issue is now fixed with new proxy version (2.5.0)
