### ISSUE TITLE
Typo (french)

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-proxy#145]
In  cozy-proxy/client/app/locales/fr.coffee :

"Vous permet d'afficher **correctement** les heures dans les événements."

**Comment by clochix** [comment]
Merci ☺
Je te laisse aller sur https://github.com/cozy/cozy-proxy/blob/development/client/app/locales/fr.coffee et cliquer sur le crayon en haut à droite pour faire la correction toi-même et ainsi ajouter ton nom au Panthéon des développeurs de l'application ;-)

**Comment by cylwin** [comment]
Thx @f6fvy 
fixed in https://github.com/cozy/cozy-proxy/commit/2543d38f965edb590dc9043097a757c1f898da59
