### ISSUE TITLE
Display a warning when DS is Down

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-proxy#152]
When the datasystem or CouchDB are not started, user is redirected to the registration form. This is pretty disturbing, as user may think they have lost their data. Displaying a message encouraging the user ton contact support or verify the status of the server would be a better experience.

**Comment by poupotte** [comment]
This issue was fixed.
Now, proxy display a warning error : 
![screenshot from 2015-11-04 08 56 08](https://cloud.githubusercontent.com/assets/2659119/10932535/e856fbf2-82d1-11e5-97cb-08e9961af505.png)

**Comment by clochix** [comment]
Nice, thanks @poupotte
