### ISSUE TITLE
At register, having a problem during the Google import breaks the flow

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-proxy#159]
When I say I want to import data from my Google account, if I am not logged with the right Google account, I can't change account without breaking the flow.

Reported by @Benibur

**Comment by poupotte** [comment]
Actually, there is a button to the right top to change gmail account. 

However, we could add a button to reopen window if user closes it not on purpose.

**Comment by poupotte** [comment]
We can now reopen window to import gmail account. I propose to close this issue. @frankrousseau, don't hesistate to reopen it if isn't unclear for you.
