### ISSUE TITLE
Wrong redirection after login when a specific redirection is set in URL

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-proxy#169]
(After a platform update)

* When I am on the login page, and that a redirection to a specific page is set: https://mycozy/login?next=/?step=welcome#config-applications
* Then I login into my Cozy
* Then the browser is redirected to "https://mycozy/%23config-applications?next=/?step=welcome#config-applications"

Expected result:
* The browser redirects to "https://mycozy/#config-applications"

Additional information:
* Proxy v2.1.1
* Browser: Chrome

**Comment by nicofrand** [comment]
This happens when restarting cozy from the status page for example.

**Comment by poupotte** [comment]
This issue should be fixed. @jsilvestre is it still revelant for you ?

**Comment by clochix** [comment]
Ping @jsilvestre

**Comment by poupotte** [comment]
Specific redirection after login works for me. I close this issue, @jsilvestre , if you have still the problem, don't hesistate to reopen this issue.
