### ISSUE TITLE
Proxy submit register request multiple times

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-proxy#174]
When registering, the registration endpoint is called multiple times, resulting of 409 errors.

**Reproduce**
1. register a new user
2. pass the leave google form (registration is sent again > 409)
3. pass email configuration form (registration is sent again > 409)

**Expected result**
The form must not be sent when passing form in next steps.

**Comment by clochix** [comment]
@m4dz this should have been fixed. Could you give the patch a try and close this ticket, please?
Thanks for reporting. Thanks @poupotte for fixing ☺

**Comment by m4dz** [comment]
Ok for me, thanks again @poupotte :smiley:!
