### ISSUE TITLE
Handle connexion problem with application

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-proxy#184]
Some time, the application is running but the connexion with it is lost, for an unknown reason (`ECONNRESET`). It may be reseted only for a single request, or for every following request. So the user get a 504 error, while the application is running.

Maybe could we add to the error page an action to try to restart the application ?

**Comment by clochix** [comment]
In fact, this happens when connections between proxy and the application are not closed cleanly. They stay in `CLOSE_WAIT` state. By default, Node only allows [five concurrent connections](https://nodejs.org/docs/latest-v0.10.x/api/http.html#http_agent_maxsockets) to the same origin, so when we reach this limit, the proxy become unable to communicate with the application, and the only solution seems to be to restart the proxy.

**Comment by nono** [comment]
See #235 and #238

**Comment by frankrousseau** [comment]
@clochix reopen this issue if the problem persists.
