### ISSUE TITLE
Allow to select language on register page

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-proxy#198]
(feedback from a user)

When an user connects for the first time, we use the headers send by its browser to select a locale. Unfortunately, sometime user would like another locale, so I think we should add to the register page a select to allow user to see registering process in another language.

**Comment by poupotte** [comment]
After discuss, we prefer keep browser locale.

Indeed, it seems logical to use browser locale and user can change it after register. Add to the register page a select for language could overload register page.
