### ISSUE TITLE
ReferenceError: next is not defined

### ISSUE THREAD

**Issue by maxlath** [cozy/cozy-proxy#202]
it seem to be [fixed here](https://github.com/cozy/cozy-proxy/blob/65b5f722fc63de9c2aabe1def675546357b679ea/build/client/public/scripts/app.js) but once I `apt-get install cozy`, I got a version with `ReferenceError: next is not defined   app.js:1085:7`
with indeed an error in the function variable definition:
```javascript
[...]
this)).onValue(function(path) {
      var loc;
      loc = window.location;
      // hereafter is the line 1085:
      return window.location.href = "" + loc.protocol + "//" + loc.host + next;
    });
    return this.add('nextControl', nextControl);
  };
[...]
```
so I guess it is just a matter of updating the apt-get package or a build script somewhere?
The sad consequence is that the "c'est parti !" button gives no effect ^^

**Comment by clochix** [comment]
Thanks for reporting @maxlath, this is a regression I introduced some days ago ☹ The fix will be published soon.

**Comment by clochix** [comment]
Hi @maxlath,

This should have been fixed for some time now.
Don't hesitate to re-open this issue if you still face this problem.
