### ISSUE TITLE
Missing url encoding of "?" when redirected to /login

### ISSUE THREAD

**Issue by khertan** [cozy/cozy-proxy#215]
Missing url encoding of "?" when redirected to /login
This prevent registering a remotestorage from litewrite.net for example (you need to logout before).

**Comment by clochix** [comment]
Thanks for reporting and fixing @khertan,

Your fix will be in the next release of the proxy, probably next week. Have you been able to test it on your server, or do you want some help to install it?

**Comment by khertan** [comment]
Thanks, it's already installed at home :) I tested it before committing ;)

**Comment by poupotte** [comment]
Thanks @khertan
