### ISSUE TITLE
Add an option to listen on https

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-proxy#217]
On small configurations (like Raspberry Pi), it would be nice to have an option to handle https inside the Cozy proxy, so user can get rid of the reverse proxy and lower memory usage.

**Comment by clochix** [comment]
Could we have a summary of what has been done? If users can now get rid of the frontend reverse proxy, it could be worth mentioning it in the documentation.

**Comment by nono** [comment]
@clochix I've added a section in the README about: https://github.com/cozy/cozy-proxy#listen-on-https. If you think that it needs more information, tell me what should be documented.

**Comment by clochix** [comment]
I think we should better explain how to start the Proxy with this environment variables. Could we just add them to /etc/cozy/controller.json ? It would be easier, but I'm not sure it would work. @poupotte, any idea of an easy way to start the proxy in TLS mode ?

**Comment by nono** [comment]
@clochix yes, you can set env for an app from this file. It's explained here: https://docs.cozy.io/en/hack/cookbooks/controller.html#configuration. Do you want to make a PR to complete the README of proxy, or should I do that?

**Comment by clochix** [comment]
I'll do.
