### ISSUE TITLE
Error message on login screen

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-proxy#240]
Reported by @nicofrand

“login undefined” is displayed on login screen.
![error screenshot](https://framapic.org/8BV0vP8v9D5z/wSFaWOmVKxpI.png) 

This is only a display problem, but gives a bad image of Cozy.

**Comment by frankrousseau** [comment]
@clochix Could you tell us in which case it occurs?

**Comment by nicofrand** [comment]
Just after the platform update.

**Comment by clochix** [comment]
Every user trying to connect with the latest version of the proxy as this erroneous error message. This doesn't prevent from logging, but may make the users think something is broken.

I think @nono already identified the source?

**Comment by nono** [comment]
Yes, I've made a PR: https://github.com/cozy/cozy-proxy/pull/241

**Comment by nono** [comment]
We have a check on `alert` and it's always true on the new version because of `window.alert`. I don't why it appeared in this version, or how it works on previous versions. I've just reinforced the check.

**Comment by frankrousseau** [comment]
@aenario Could you publish this fix?
