### ISSUE TITLE
Making replication happens through DS

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-proxy#44]
Currently the replications (in this case, requests from a device) are proxied to CouchDB directly instead of going through the Data System.

It has been done this way since the double proxy was not working. We should try with the new http-proxy version.

We could have external clients using the data system directly, which is great, I think.

**Comment by nono** [comment]
@jsilvestre is it still the case?

**Comment by jsilvestre** [comment]
@poupotte has worked on that, but I don't know to which extent it's done. Can you please expand on that a bit for @nono? Thanks!

**Comment by poupotte** [comment]
Currently, proxy and data-system have an API to replicate throught DS. This API has a permission system for device registered on Cozy. 
However, for the moment, mobile application doesn't use this API. Temporary, device can replicate directly with couch or use the new API. When mobile application will be up to date, we'll remove the old route.

**Comment by nono** [comment]
Thanks!
