### ISSUE TITLE
Express guide recommendation

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-proxy#83]
Just read that on the express documentation. That's something to investigate later:

Express behind proxies

Using Express behind a reverse proxy (such as Varnish or Nginx) is trivial; however, it does require configuration. By enabling the "trust proxy" setting via app.enable('trust proxy'), Express will have knowledge that it's sitting behind a proxy and that the X-Forwarded-* header fields may be trusted. (Otherwise, they are easily spoofed.)

Enabling this setting has several subtle effects. The first is that X-Forwarded-Proto may be set by the reverse proxy to tell the app whether it is https or simply http. This value is reflected by req.protocol.

The second change is that the req.ip and req.ips values will be populated with X-Forwarded-For's list of addresses.

**Comment by nono** [comment]
@frankrousseau I think we can close this issue. We don't have nginx configured to send these `X-Forwarded-For-*` headers. And we don't have any usage for them (for the protocol, it's https only, and for the user IP, execpt in nginx logs, I don't see why we want it).

**Comment by clochix** [comment]
This may be useful for #214 (add informations to the reset password email).
Also, some applications, like Ghost, may want to access the end user IP to gather some statistics.

**Comment by frankrousseau** [comment]
Let's close it. The Ghost use case is not interesting yet and the reset password use case has already a dedicated ticket.
