### ISSUE TITLE
"Something went wrong" when opening a stopped application

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-proxy#95]
I often access my applications directly by typing "https://mycozy.tld/apps/{appName}/", and I noticed that I often get an error message, whereas if I reload the page instantly, I get the application.

I suspect the proxy to throw an error too fast, without waiting for the application to be started (I wrote this code, so I suspect it a lot :D)

**Comment by cylwin** [comment]
This issue seems to be solved, isn't it ?

**Comment by poupotte** [comment]
Seems ok for me. @jsilvestre is it fixed for you ?

**Comment by clochix** [comment]
Hi @jsilvestre, sorry to awake you, could we close this one please? Our statistics would love it!

**Comment by poupotte** [comment]
This issue seems fixed sine some time. I close this issue. @jsilvestre , if you have still the problem, don't hesistate to reopen this issue.
